services:
  - type: web
    name: bot-whatsapp-sion
    buildCommand: "npm install"
    startCommand: "npm start"
    env:
      - key: PUPPETEER_CACHE_DIR
        value: "/tmp"
    plan: free
    region: oregon
